package com.yash.entities;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(3a6d9bd8c6620a3b0fa4b89e31699420)
 */
@org.kie.api.definition.type.Label(value = "Movie")
public class Movie  implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Movie() {
    }




}