package com.yash.entities;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(b1ea25cdd475a7dbb5fc04bb1315df8f)
 */
@org.kie.api.definition.type.Label(value = "Movie")
public class Movie  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Actor")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String actor;

    public Movie() {
    }

    public Movie(java.lang.String actor) {
        this.actor = actor;
    }


    
    public java.lang.String getActor() {
        return this.actor;
    }

    public void setActor(java.lang.String actor) {
        this.actor = actor;
    }
}